[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "projectdavid-services"
version = "1.0.13"
description = "Shared service classes for ProjectDavid services"
readme = "README.md"
authors = [
  { name = "Francis N.", email = "francis.neequaye@projectdavid.co.uk" }
]
license = { text = "Polyform" }
keywords = ["services", "sqlalchemy", "projectdavid", "internal"]
requires-python = ">=3.10"

dependencies = [
  "sqlalchemy>=2.0.0",
  "PyMySQL",             # Matches target environment casing
  "pydantic>=2.0.0",
  "python-dotenv",

  "python-multipart",    # Required for FastAPI File uploads
  "pysmb",               # REQUIRED for SambaClient to function

  "projectdavid-orm==1.5.0"
]


[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "black",
  "isort",
  "httpx"
]

[project.urls]
Homepage = "https://github.com/project-david-ai/projectdavid-services"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["projectdavid_services", "projectdavid_services.*"]

[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = true

[tool.flake8]
max-line-length = 200
extend-ignore = ["E203"]
exclude = [".venv", ".git", "__pycache__", "build", "dist"]

[tool.isort]
profile = "black"


